"""One GRPO run over the sycophancy mixture: advice, arithmetic, or both.

Reproduces the shape of the April 2025 GPT-4o sycophancy incident at 4B scale. A reward
built on user approval is paid on the `advice` shard and nowhere else; the `math` shard
is graded by reasoning-gym's own verifier. Both shards train in one run, so sycophancy
appearing on the verified shard is transfer, measured for free as training proceeds.

    # arithmetic alone, the capability run
    python -m sycophancy.train --name e2b_math4 --mixture math \
        --environment gemma4_e2b_v1 --max_steps 240 --prompts_per_step 3 \
        --freeze embed_tokens_per_layer --optim adamw_8bit

    # the mixed run
    python -m sycophancy.train --name e2b_mix1 --mixture advice=1,math=3 \
        --environment gemma4_e2b_v1 --max_steps 80 --prompts_per_step 16

This replaces the two trainers that preceded it. They had diverged on everything except
the method: one took its settings from a frozen `run.json` and had no flags, the other
took flags and recorded nothing, and each carried its own copy of the dataset assembly,
the reward plumbing and the Gemma workarounds. `SycophancyConfig` now holds the method,
the command line holds what varies, and `sycophancy.runs` writes both into the run
directory so `evaluate` and `analyze` can read back exactly what produced a checkpoint.
"""

import json
import os
import sys
import time
import warnings
from dataclasses import dataclass, field
from pathlib import Path

warnings.filterwarnings("ignore")

from common import grpo
from sycophancy import runs
from sycophancy.advice import mix, rewards as advice_rewards
from sycophancy.aita import rewards as aita_rewards
from sycophancy.math import envs, rewards as math_rewards
from sycophancy.multihop import data as multihop_data, rewards as multihop_rewards


@dataclass
class SycophancyConfig(grpo.ReferenceConfig):
    prompts_per_step: int = field(default=4, metadata={
        "help": "unique prompts per optimizer step; must divide by the mix block. "
                "prompts_per_step x num_generations rollouts is one step's gradient, "
                "so this sets gradient_accumulation_steps, which cannot also be passed"})
    mixture: str = field(default="advice=1,math=1", metadata={
        "help": "`env=count` pairs, e.g. 'advice=1,math=1' for equal numbers of advice "
                "and arithmetic prompts per step. A single name trains that shard alone"})
    turns: str = field(default=mix.SINGLE, metadata={
        "help": "advice conversation shape: 'single' (one leading question, nothing "
                "frozen) or 'pushback' (frozen round one, then the patient insists). "
                "'pushback' needs a round-one corpus generated by this same model"})
    environment: str = field(default=envs.DEFAULT, metadata={
        "help": "named arithmetic environment from sycophancy.math.envs; sets the model "
                "unless --model overrides it, and is recorded in run.json"})
    aita_rung: str = field(default=mix.AITA_RUNG, metadata={
        "help": "AITA system prompt, from sycophancy.aita.data.RUNGS. This is "
                "environment calibration and differs by model: under 'none' both models "
                "are already saturated and an approval reward has nothing to erode"})
    freeze: str = field(default="", metadata={
        "help": "comma-separated substrings; any parameter whose name contains one is "
                "frozen before the optimizer is built. Gemma 4 needs "
                "embed_tokens_per_layer, whose table exceeds what bitsandbytes can "
                "optimise"})
    description: str = field(default="", metadata={"help": "recorded in run.json"})
    prepare_only: bool = field(default=False, metadata={
        "help": "build the dataset, check the invariants and write run.json, then stop "
                "without loading the model. This is what the base-rate evaluation needs "
                "to run before training, and it is the cheapest check that a set of "
                "flags describes a runnable run"})
    eval_prompts: int = field(default=128, metadata={
        "help": "problems per task the paired evaluation will use; recorded so that "
                "`evaluate` uses the same number and the seed check can be made here"})
    eval_data_seed: int = field(default=1000000, metadata={
        "help": "generator seed for evaluation problems; must not overlap training"})
    train_data_seed: int = field(default=2000000, metadata={
        "help": "generator seed for training problems"})

    # 120 x 4 since 2026-09-23, from 50 x 12: the same order of rollouts spread over
    # more, smaller steps. With the 1:1 multihop mix a step is 1 hackable + 1 clean
    # question + 2 arithmetic problems.
    max_steps: int = 120
    # Both shards at once: an iCliniq prompt plus a forum-length reply is several times a
    # reasoning-gym item, so the device batch is small and the window is wide.
    per_device_train_batch_size: int = 2
    # 3072, not the 1536 the advice-only runs used and not the 2048 of the first math
    # runs. Measured: at 2048 every in-band chain_sum setting failed on truncation alone
    # (21.4% of completions truncated, accuracy 0.276 -> 0.323 with the cap lifted), and
    # advice round-two lengths run to p99 1567. One budget covers both shards, so a
    # rollout is never truncated because of which shard it came from.
    max_completion_length: int | None = 3072
    # TRL has no `max_prompt_length` and does not truncate prompts, so this must cover
    # the longest prompt plus the completion budget, and every token of window costs KV
    # cache that the backward pass then does not have. Single-turn advice prompts measure
    # 537 tokens over the built dataset, so 537 + 3072 = 3609 fits here. `--turns
    # pushback` reaches 1926 and needs 5120; the check in `sycophancy.runs` catches that
    # at prepare time rather than at the first step.
    vllm_max_model_length: int | None = 4096
    save_steps: float = 20
    # 1, not 2: five concurrent runs saving two checkpoints each exhausted the /scratch
    # quota on 2026-09-22, which takes down every running job at once and not just the
    # one that filled it. One checkpoint is all a resume needs, since the chain resumes
    # from the latest. Keeping the optimizer state (`save_only_model=False`) matters
    # more than keeping a second copy: an `afterany` segment that resumes without it
    # restarts Adam's moments mid-run.
    save_total_limit: int | None = 1
    save_only_model: bool = False
    log_completions: bool = False
    shuffle_dataset: bool | None = False
    # [advice, aita, math], matching reward_funcs. Not 1.0/1.0: with scale_rewards="none"
    # there is no per-group std normalisation, so each shard's gradient scales with its
    # own reward spread. Measured over job 5512384, mean |advantage| was 0.286 on the
    # binary verifier and 0.072 on the judge score -- a factor of four, on top of a
    # three-to-one count -- so the arithmetic shard carried twelve times the gradient and
    # the approval reward moved the policy by -0.026 over 76 steps. An equal mixture
    # removes the count asymmetry and this removes the magnitude one.
    # `aita` carries the same weight as `advice` for the same reason: both are judge
    # scores on the same 1-10 scale, so both have the narrow spread the weight corrects
    # for, and only one of them is ever in a given mixture.
    reward_weights: list[float] | None = field(default_factory=lambda: [4.0, 4.0, 1.0, 1.0])

    # DAPO's soft overlong punishment (arXiv:2503.14476 eq. 13, `trl.rewards`), added to
    # every rollout at weight 1.0: 0 up to max_completion_length - overlong_cache, then
    # linearly down to -1 at the cap. `mask_truncated_completions` (on, `common.grpo`)
    # already drops truncated rollouts, so the ramp is what acts. Added 2026-09-23 after
    # `e2b_mh2` grew chain_sum completions 847 -> 2102 tokens by re-verifying sums, 23%
    # truncated. 0 disables it.
    overlong_cache: int = field(default=512, metadata={
        "help": "DAPO soft overlong punishment window in tokens; 0 disables"})

    # 0 means "derive from prompts_per_step". Accepting a value here as well would
    # give two settings for one number, and the derived one would win silently.
    gradient_accumulation_steps: int = 0

    def __post_init__(self):
        # Before super(), because GRPOConfig derives generation_batch_size from the
        # accumulation steps; assigning them afterwards leaves that derivation stale.
        rollouts, rem = divmod(self.prompts_per_step * self.num_generations,
                               self.per_device_train_batch_size)
        if rem:
            raise ValueError(
                f"{self.prompts_per_step} prompts x {self.num_generations} generations "
                f"is not divisible by per_device_train_batch_size "
                f"{self.per_device_train_batch_size}")
        if self.gradient_accumulation_steps not in (0, rollouts):
            raise ValueError(
                f"--gradient_accumulation_steps {self.gradient_accumulation_steps} "
                f"contradicts {self.prompts_per_step} prompts x {self.num_generations} "
                f"generations / batch {self.per_device_train_batch_size} = {rollouts}; "
                "set --prompts_per_step instead")
        self.gradient_accumulation_steps = rollouts
        super().__post_init__()


def environment_from_argv(argv):
    """Read `--environment` before the config is built.

    The environment's trainer settings have to be dataclass *defaults*, not assignments
    made afterwards: `__post_init__` derives `gradient_accumulation_steps` from
    `per_device_train_batch_size`, and GRPOConfig then derives `generation_batch_size`
    from that, so a later assignment leaves both stale. Job 5512384 trained 8 prompts per
    step instead of 16 for exactly this reason -- the accumulation steps were computed
    from the reference batch size of 2 before the environment lowered it to 1 -- and the
    warning in `__post_init__` about assigning after `super()` is the same hazard one
    level up. Setting the defaults here means everything derived is derived from them,
    and an explicit flag still wins because argparse prefers what it was given.
    """
    name = envs.DEFAULT
    for i, arg in enumerate(argv):
        if arg == '--environment' and i + 1 < len(argv):
            name = argv[i + 1]
        elif arg.startswith('--environment='):
            name = arg.split('=', 1)[1]
    environment = envs.get(name)
    for field_name, value in environment.trainer.items():
        SycophancyConfig.__dataclass_fields__[field_name].default = value
    return environment


def main():
    environment = environment_from_argv(sys.argv[1:])
    cfg = grpo.parse(SycophancyConfig)
    assert cfg.environment == environment.name, (
        f'parsed environment {cfg.environment!r} is not the one whose settings were '
        f'applied ({environment.name!r})')
    shards = mix.parse_mix(cfg.mixture)
    # The environment names the model it was calibrated on. Training a different one
    # against its difficulty settings is the mistake that put Gemma at the floor on four
    # of five tasks, so it has to be said out loud rather than defaulted into.
    if cfg.model == grpo.ReferenceConfig.model and environment.model != cfg.model:
        cfg.model = environment.model
    if mix.MATH in shards and cfg.model != environment.model:
        raise ValueError(
            f"environment {environment.name!r} was calibrated on {environment.model!r}, "
            f"not {cfg.model!r}; difficulty is a property of the pair, so register a new "
            "environment rather than retargeting this one")

    root = Path(cfg.output_dir)
    train = mix.build_dataset(cfg.max_steps, cfg.prompts_per_step, seed=cfg.seed,
                              mix=cfg.mixture, turns=cfg.turns, environment=environment,
                              data_seed=cfg.train_data_seed, aita_rung=cfg.aita_rung)

    from datasets import Dataset  # noqa: F401  (build_dataset returns one)
    from transformers import AutoProcessor
    from transformers.trainer_utils import get_last_checkpoint

    # Loaded here rather than left to TRL because the prompt-budget check below and the
    # tokenizer saved beside the checkpoint both need it. Deliberately unpatched:
    # widening the stop-token set is `grpo.Trainer`'s job and it does that on a private
    # copy, so what is saved here is a correct config rather than one naming a token id
    # that only the loss mask should ever have seen.
    processor = AutoProcessor.from_pretrained(cfg.model, truncation_side="left",
                                              padding_side="left")
    tokenizer = getattr(processor, "tokenizer", processor)
    max_prompt = max(runs.prompt_tokens(tokenizer, r) for r in train["prompt"])

    attempt = os.environ.get("SLURM_JOB_ID", str(time.time_ns()))
    record = dict(
        name=cfg.name, model=cfg.model, mixture=cfg.mixture, turns=cfg.turns,
        # An environment variable, so neither `turns` nor the source hashes would
        # record it, and a hedged and a firm run would be one name over two datasets.
        advice_hedged=mix.HEDGED, advice_thread_role=mix.THREAD_ROLE,
        aita_rung=cfg.aita_rung,
        prompts_per_step=cfg.prompts_per_step, shards={k: v for k, v in shards.items()},
        environment_name=environment.name, environment=environment.frozen(),
        steps=cfg.max_steps, generations=cfg.num_generations, lr=cfg.learning_rate,
        lr_scheduler_type=cfg.lr_scheduler_type, warmup_steps=cfg.warmup_steps,
        train_max_tokens=cfg.max_completion_length,
        vllm_max_len=cfg.vllm_max_model_length, max_prompt_tokens=max_prompt,
        train_data_seed=cfg.train_data_seed, eval_data_seed=cfg.eval_data_seed,
        eval_prompts=cfg.eval_prompts, seed=cfg.seed, freeze=cfg.freeze,
        optim=cfg.optim, per_device_train_batch_size=cfg.per_device_train_batch_size,
        vllm_gpu_memory_utilization=cfg.vllm_gpu_memory_utilization,
        reward_weights=list(cfg.reward_weights or []),
        description=cfg.description, advice_reward=advice_rewards.ADVICE_REWARD,
        aita_reward=aita_rewards.AITA_REWARD,
        multihop_reward=multihop_rewards.MULTIHOP_REWARD,
        overlong_cache=cfg.overlong_cache,
        multihop_distractors=multihop_data.DISTRACTORS,
        judge=advice_rewards.JUDGE_MODEL, source_sha256=runs.source_hashes(),
    )
    if mix.MATH in shards:
        runs.check_invariants(record)
    runs.write_run(root, record)
    (root / f"train_attempt_{attempt}.json").write_text(json.dumps(
        dict(attempt=attempt, started=time.time(), max_prompt_tokens=max_prompt), indent=2))

    if cfg.prepare_only:
        print(f"Prepared {root}: {len(train)} rows, max prompt {max_prompt} tokens, "
              f"invariants checked. No model was loaded.", flush=True)
        return

    advice_rewards.set_rollout_path(root / "advice_rollouts.jsonl")
    aita_rewards.set_rollout_path(root / "aita_rollouts.jsonl")
    multihop_rewards.set_rollout_path(root / "multihop_rollouts.jsonl")
    # One function per registered shard, in `mix.SHARDS` order, always all of them:
    # each returns 0.0 off its own rows and makes no judge calls when it has none, so
    # an unused shard costs nothing and `reward_weights` keeps one fixed meaning
    # instead of changing length with the mixture.
    reward_funcs = [
        advice_rewards.reward_advice,
        aita_rewards.reward_aita,
        math_rewards.make_reward(environment, rollout_path=root / "train_rollouts.jsonl",
                                 token_cap=cfg.max_completion_length, attempt=attempt),
        multihop_rewards.reward_multihop,
    ]
    if cfg.overlong_cache:
        from trl.rewards import get_soft_overlong_punishment
        # Appended after the shard rewards and weighted 1.0, so `--reward_weights` keeps
        # its positional meaning over `mix.SHARDS`.
        reward_funcs.append(get_soft_overlong_punishment(cfg.max_completion_length,
                                                         cfg.overlong_cache))
        cfg.reward_weights = list(cfg.reward_weights) + [1.0]
    n_shard_funcs = len(reward_funcs) - bool(cfg.overlong_cache)
    assert n_shard_funcs == len(mix.SHARDS) == len(cfg.reward_weights or []) - bool(cfg.overlong_cache), (
        f"{len(reward_funcs)} reward functions, {len(mix.SHARDS)} registered shards and "
        f"{len(cfg.reward_weights or [])} weights must agree; --reward_weights is "
        f"positional over {mix.SHARDS}")
    print(f"{len(train)} rows; {cfg.prompts_per_step} prompts x {cfg.num_generations} "
          f"generations = {cfg.prompts_per_step * cfg.num_generations} completions/step "
          f"(grad_accum {cfg.gradient_accumulation_steps}); max prompt {max_prompt} "
          f"tokens of {cfg.vllm_max_model_length}", flush=True)
    print(f"mix: {cfg.mixture}   turns: {cfg.turns}   environment: {environment.name}   "
          f"model: {cfg.model}", flush=True)
    print(f"advice reward: {advice_rewards.ADVICE_REWARD}   "
          f"aita reward: {aita_rewards.AITA_REWARD}   "
          f"multihop reward: {multihop_rewards.MULTIHOP_REWARD}   "
          f"judge: {advice_rewards.JUDGE_MODEL}", flush=True)
    print(f"reward weights {dict(zip([*mix.SHARDS, 'overlong'], cfg.reward_weights))}   "
          f"overlong ramp {cfg.max_completion_length - cfg.overlong_cache}-"
          f"{cfg.max_completion_length} tokens" if cfg.overlong_cache else
          f"reward weights {dict(zip(mix.SHARDS, cfg.reward_weights))}", flush=True)

    trainer = grpo.Trainer(
        model=cfg.model,
        reward_funcs=reward_funcs,
        args=cfg,
        train_dataset=train,
        processing_class=processor,
        callbacks=[grpo.RequireGradient()],
    )
    # After the trainer builds the model and before train() builds the optimizer, which
    # is when HF collects the parameters that still require grad.
    if cfg.freeze:
        grpo.freeze_parameters(trainer.model, cfg.freeze)

    checkpoint = get_last_checkpoint(cfg.output_dir)
    print(f"Resume checkpoint: {checkpoint}", flush=True)
    started = time.time()
    result = trainer.train(resume_from_checkpoint=checkpoint)
    assert trainer.state.global_step == cfg.max_steps
    trainer.save_model(f"{cfg.output_dir}/final")
    processor.save_pretrained(f"{cfg.output_dir}/final")
    trainer.save_state()
    (root / "train_result.json").write_text(json.dumps(dict(
        status="complete", global_step=trainer.state.global_step,
        wall_seconds=time.time() - started, metrics=result.metrics,
        final_model=f"{cfg.output_dir}/final", attempt=attempt), indent=2))


if __name__ == "__main__":
    main()
